// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Tue Apr 30 03:44:38 2024

twoBitUpCounterREAL twoBitUpCounterREAL_inst
(
	.CLRN1(CLRN1_sig) ,	// input  CLRN1_sig
	.CLK1(CLK1_sig) ,	// input  CLK1_sig
	.EnableReal(EnableReal_sig) ,	// input  EnableReal_sig
	.Q0(Q0_sig) ,	// output  Q0_sig
	.Q1(Q1_sig) ,	// output  Q1_sig
	.Q3(Q3_sig) 	// output  Q3_sig
);

